language: cpp

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - libblas-dev
      - liblapack-dev
      - gromacs-dev
      - openmpi-bin
      - libopenmpi-dev

before_install:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/ProtoMol -DBUILD_LAPACK_TYPE=lapack -DBUILD_GROMACS=ON -DBUILD_PARALLEL=ON -DCODE_COVERAGE=ON
  - cmake -DMPI_C_LINK_FLAGS="" -DMPI_CXX_LINK_FLAGS=""
  - make
  - make install
  - cd test
  - cp $HOME/ProtoMol/bin/ProtoMol .
  - python test.py --serial --parallel --errorfailure

after_success:
  - find /home/travis/build/Omegaice/ProtoMol -type f -name '*.gcno'
  - bash <(curl -s https://codecov.io/bash)
