language: cpp

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - lcov
      - libblas-dev
      - liblapack-dev
      - gromacs-dev
      - openmpi-bin
      - libopenmpi-dev

before_install:
  - gem install lcoveralls

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/ProtoMol -DBUILD_LAPACK_TYPE=lapack -DBUILD_GROMACS=ON -DBUILD_PARALLEL=ON -DCODE_COVERAGE=ON
  - cmake -DMPI_C_LINK_FLAGS="" -DMPI_CXX_LINK_FLAGS=""
  - make
  - make install
  - lcov --directory . --zerocounters
  - cd test
  - cp $HOME/ProtoMol/bin/ProtoMol .
  - python test.py --serial --parallel --errorfailure

after_success:
  - lcov -q --directory .. --capture --output-file coverage.info
  - lcov -q --remove coverage.info '/usr/*' '*OpenMM/include*' --output-file coverage.info.clean
  - lcoveralls --root $TRAVIS_BUILD_DIR
