language: cpp

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - lcov
      - libblas-dev
      - liblapack-dev
      - gromacs-dev
      - openmpi-bin
      - libopenmpi-dev

before_install:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/ProtoMol -DBUILD_LAPACK_TYPE=lapack -DBUILD_GROMACS=ON -DBUILD_PARALLEL=ON -DCODE_COVERAGE=ON ..
  - cmake -DMPI_C_LINK_FLAGS="" -DMPI_CXX_LINK_FLAGS="" ..
  - make
  - make install
  - lcov --directory . --zerocounters
  - cd ../test
  - cp $HOME/ProtoMol/bin/ProtoMol .
  - python test.py --serial --parallel --errorfailure

after_success:
  - cd ..
  - lcov -q --list-full-path --directory build --capture --output-file coverage.info
  - lcov -q --list-full-path --remove coverage.info '/usr/*' '*OpenMM/include*' --output-file coverage.info.clean
  - npm install coveralls
  - cat coverage.info.clean | ./node_modules/coveralls/bin/coveralls.js
